name: Tests

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    name: Building on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest # x64
          - os: ubuntu-24.04-arm # arm64
          - os: macos-latest # arm64
          - os: macos-13 # x64 
    steps:
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/nix-installer-action@main
    - uses: cachix/cachix-action@v14
      with:
        name: twesterhout
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Build
      run: |
        nix build --accept-flake-config -L
  deploy:
    name: Create artifacts
    runs-on: ubuntu-latest
    steps:
    - uses: DeterminateSystems/nix-installer-action@main
    - name: Build
      run: |
        nix build github:twesterhout/phd-thesis --accept-flake-config -L
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: Thesis
        path: 'result/*.pdf'
